### ISSUE TITLE
How is the default password?

### ISSUE THREAD

**Issue by maverick504** [wmucheru/ci-admin-website-boilerplate#1]
Hello Mr, I would like to try your CodeIgniter boilerplate but I cannot log-in with the default admin user (admin@example.com), because I don't know his password.

Can you provide me the password?

Thank you very much. ^^

**Comment by wmucheru** [comment]
Hi! The default password is `123456`

**Comment by EmilianoJaimes** [comment]
😮

It works! I've tried `admin`, `password` and `12345689`, but not `123456`. 😅

Thanks!
